version: '3.2'
services:
  php:
    build: 
      context: php
    restart: always
    ports:
      - "9001:9000"
    volumes:
      - type: bind
        source: ./app
        target: /app
    networks: 
      php-nginx:
        aliases:
         - php
  nginx:
    image: "nginx:1.16"
    volumes: 
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: ./nginx/conf.d/
        target: /etc/nginx/conf.d
    ports:
      - "80:80"
    networks: 
      php-nginx:
        aliases:
         - nginx
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes: 
      - type: bind
        source: ./data
        target: /var/lib/mysql
    ports:
      - 3306:3306
    networks: 
      php-nginx:
        aliases:
         - mysql
  memcached:
    image: memcached:1.5
    restart: always
    ports:
      - 11211:11211
    networks: 
      php-nginx:
        aliases:
         - memcached
networks:
  php-nginx: